// generated by stringer -output types_items_string.go -type=ItemType; DO NOT EDIT

package evego

import "fmt"

const _ItemType_name = "UnknownItemTypeOreIceOther"

var _ItemType_index = [...]uint8{0, 15, 18, 21, 26}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return fmt.Sprintf("ItemType(%d)", i)
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
