// generated by stringer -output types_standings_string.go -type=StandingType; DO NOT EDIT

package evego

import "fmt"

const _StandingType_name = "UnknownEntityNPCFactionNPCCorporationNPCAgentPlayerCharacterPlayerCorporationPlayerAlliance"

var _StandingType_index = [...]uint8{0, 13, 23, 37, 45, 60, 77, 91}

func (i StandingType) String() string {
	if i < 0 || i+1 >= StandingType(len(_StandingType_index)) {
		return fmt.Sprintf("StandingType(%d)", i)
	}
	return _StandingType_name[_StandingType_index[i]:_StandingType_index[i+1]]
}
