// generated by stringer -output items_string.go -type=ItemType; DO NOT EDIT

package types

import "fmt"

const _ItemType_name = "OreIceOther"

var _ItemType_index = [...]uint8{3, 6, 11}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)) {
		return fmt.Sprintf("ItemType(%d)", i)
	}
	hi := _ItemType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ItemType_index[i-1]
	}
	return _ItemType_name[lo:hi]
}
