// generated by stringer -output market_string.go -type=OrderType,OrderRange; DO NOT EDIT

package types

import "fmt"

const _OrderType_name = "BuySellAllOrders"

var _OrderType_index = [...]uint8{3, 7, 16}

func (i OrderType) String() string {
	if i < 0 || i >= OrderType(len(_OrderType_index)) {
		return fmt.Sprintf("OrderType(%d)", i)
	}
	hi := _OrderType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _OrderType_index[i-1]
	}
	return _OrderType_name[lo:hi]
}

const _OrderRange_name = "BuyStationBuySystemBuyNumberJumpsBuyRegion"

var _OrderRange_index = [...]uint8{10, 19, 33, 42}

func (i OrderRange) String() string {
	if i < 0 || i >= OrderRange(len(_OrderRange_index)) {
		return fmt.Sprintf("OrderRange(%d)", i)
	}
	hi := _OrderRange_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _OrderRange_index[i-1]
	}
	return _OrderRange_name[lo:hi]
}
